version: '3'
services:
  bot:
    volumes:
      - ./Commands:/home/Commands
      - ./mechanics:/home/mechanics
      - ./Static:/home/Static
      - ./nekobot.py:/home/nekobot.py
      - ./requirements.txt:/home/requirements.txt